name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get current branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_ENV
          echo "Branch: $branch"
      - name: Exit if not on main branch
        run: |
          if [ "${{ env.branch }}" != "main" ]; then
            echo "Error: Branch is not main"
            exit 1
          fi
      - name: Done
        run: echo Done deploying
