name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get branch
        # echo "BRANCH=$branch" >> $GITHUB_ENV
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "$branch"
      # - name: Print branch
      #   run: echo ${{ env.BRANCH }}
      # - name: Exit if not on main branch
      #   if: endsWith(${{ env.BRANCH }}, 'main') == false
      #   run: exit -1
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Done
        run: echo Done deploying
