name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Get branch test
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event.base_ref: ${{ github.event.base_ref }}"
      - name: Get current branch
        id: get_current_branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Branch: $branch"
      - name: Exit if not on main branch
        if: ${{ steps.get_current_branch.outputs.branch != 'main' }}
        run: |
          echo "Exit because not on main branch"
          exit 1
      - name: Done
        run: echo Done deploying
